development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  #adapter: redis
  #url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  #channel_prefix: spex_production
